### ISSUE TITLE
文件在手机上能打开，在3288开发板打不开

### ISSUE THREAD

**Issue by dongweiq** [Victory-Over/SuperWeb#10]
`12-06 16:34:50.131 28029-28029/? I/art: Late-enabling -Xcheck:jni
12-06 16:34:50.179 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.180 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.184 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.185 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.291 28029-28049/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.293 28029-28049/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.295 28029-28049/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.334 28029-28029/com.fanneng.android.web.demo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-06 16:34:50.358 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.368 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.369 28029-28029/com.fanneng.android.web.demo D/PhoneWindow: DecorView - SCREEN_WEITH = 1080 - SCREE_HEIGHT = 1872
12-06 16:34:50.458 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.460 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.462 28029-28054/com.fanneng.android.web.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-06 16:34:50.465 28029-28029/com.fanneng.android.web.demo D/Atlas: Validating map...
12-06 16:34:50.465 28029-28029/com.fanneng.android.web.demo W/Atlas: Pointer 0x0, not in getPreloadedDrawables?
12-06 16:34:50.465 28029-28029/com.fanneng.android.web.demo W/Atlas: Pointer 0x0, not in getPreloadedDrawables?
12-06 16:34:50.470 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:50.470 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#100 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@1579c021}
12-06 16:34:50.485 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#110 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@1579c021}
12-06 16:34:50.486 28029-28054/com.fanneng.android.web.demo I/mali_so: [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 780; [Func] : base_context_deal_with_version_affairs_rk_ext;
    arm_release_ver of this mali_so is 'r6p0-02rel0', rk_so_ver is '11@0', built at '16:20:19' for 3288w, on 'Aug  1 2016'.
12-06 16:34:50.486 28029-28054/com.fanneng.android.web.demo I/mali_so: [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 807; [Func] : base_context_deal_with_version_affairs_rk_ext;
    mali_ver_property has been set to 'r6p0-02rel0-13-11@0', to return.
12-06 16:34:50.488 28029-28054/com.fanneng.android.web.demo I/OpenGLRenderer: Initialized EGL, version 1.4
12-06 16:34:50.497 28029-28054/com.fanneng.android.web.demo D/OpenGLRenderer: Enabling debug mode 0
12-06 16:34:55.939 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:55.939 28029-28029/com.fanneng.android.web.demo D/PhoneWindow: DecorView - SCREEN_WEITH = 1080 - SCREE_HEIGHT = 1872
12-06 16:34:55.971 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:55.971 28029-28029/com.fanneng.android.web.demo D/PhoneWindow: DecorView - SCREEN_WEITH = 1080 - SCREE_HEIGHT = 1872
12-06 16:34:56.269 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:56.272 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#100 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@2c0ec9cb}
12-06 16:34:56.283 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#110 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@2c0ec9cb}
12-06 16:34:56.379 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutnull
12-06 16:34:56.647 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#20 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@1579c021}
12-06 16:34:58.018 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:58.018 28029-28029/com.fanneng.android.web.demo D/PhoneWindow: DecorView - SCREEN_WEITH = 1080 - SCREE_HEIGHT = 1872
12-06 16:34:58.045 28029-28029/com.fanneng.android.web.demo E/TbsReaderView: not supported by:docx
12-06 16:34:58.047 28029-28029/com.fanneng.android.web.demo D/DisplayManager: getDisplayInfo: displayId=0, info=DisplayInfo{"内置屏幕", uniqueId "local:0", app 1080 x 1872, real 1080 x 1920, largest app 1920 x 1847, smallest app 1080 x 1007, 65.202 fps, supportedRefreshRates [65.202], rotation 3, density 160 (159.89508 x 160.42105) dpi, layerStack 0, appVsyncOff 0, presDeadline 16336952, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
12-06 16:34:58.051 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#100 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@bf07f49}
12-06 16:34:58.064 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#120 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@bf07f49}
12-06 16:34:58.155 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutnull
12-06 16:34:58.432 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#20 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@2c0ec9cb}
12-06 16:35:00.918 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(fillxfill)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=260 sim=#10 ty=1 fl=#81810100 wanim=0x1030469 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2packageName=com.fanneng.android.web.demotoken=android.os.BinderProxy@2c0ec9cb}
12-06 16:35:01.023 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: 1080<<<<<< BACK FROM relayoutnull
12-06 16:35:01.130 28029-28029/com.fanneng.android.web.demo D/ViewRootImpl: onDetachedFromWindow ungister contentObserver
`

**Comment by dongweiq** [comment]
我把程序安装到手机上是可以打开文件的，但是在3288的安卓开发板上打不开，报错提示TbsReaderView: not supported by:docx，应该是x5内核没有加载成功，随后我又安装了微信和qq，也不能加载成功，目前还不太清楚是什么原因

**Comment by Victory-Over** [comment]
你是自己写的demo吗？  这个加了没
 splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk true
        }
    }

**Comment by dongweiq** [comment]
就是用的你的demo，手机上可以加载出来，但是我们的开发版不行，跟开发版接的以太网有关系吗？我后面把默认下载x5内核设置为ture也不行
  QbSdk.setDownloadWithoutWifi(true);
我去对初始化的每个回调方法打日志，发现并没有任何日志返回，但就是手机上都能返回

**Comment by Victory-Over** [comment]
跟网络没关系，应该是X5不兼容吧，你用原生的webview试试

**Comment by dongweiq** [comment]
找到原因了，因为我们的3288不是用的wifi网络，还是插的网线（以太网），然后x5的jar包里有个判断是如果是非wifi网络则不下载x5内核，也不会共享，即使设置了bSdk.setDownloadWithoutWifi(true);也无效，最后的解决方式是解压jar包，拿到class文件，修改class文件里判断网络的逻辑，然后把class文件再压缩回jar包中，使用这个jar包就可以正常下载x5内核了

**Comment by Victory-Over** [comment]
👍👍👍

**Comment by SuqinXiao** [comment]
能否发一下修改后的class，个人水平有限，编译不了修改后的代码了，791677420@qq.com，感谢
