### ISSUE TITLE
ActionActivity 盖在最顶层，透明的！！

### ISSUE THREAD

**Issue by yeqinfu** [Victory-Over/SuperWeb#16]
突然发现点击界面没反应。找了好久原来是你内部启动了这个activity盖在上面，然后是透明的，什么都没有。我去。

**Comment by Victory-Over** [comment]
ActionActivity 是用于获取权限的，获取完毕会自动关闭

**Comment by yeqinfu** [comment]
是啊，不知道为什么，在5.0进入百度首页申请了定位权限，然后用项目中的superwebx5fragment。弹窗没有出来，但是actionactivity已经出来了

**Comment by yeqinfu** [comment]
我应该找到原因了。因为我在清单没有申请
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
`

这个权限，然后进入百度，申请的就是这个权限。但是因为清单没有声明。然后这个ActionActivity弹出来了，然后权限框并没有弹出来，导致webview页面好像划不动。
所以如果真的是因为这样。那这应该是一个bug。
