### ISSUE TITLE
Failed to resolve: com.github.Victory-Over:SuperWeb:v1.0.0

### ISSUE THREAD

**Issue by jiangzehui** [Victory-Over/SuperWeb#2]
allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }

    }
}

 compile 'com.github.Victory-Over:SuperWeb:v1.0.0'

我是这样子做的，但是报错。。。Failed to resolve: com.github.Victory-Over:SuperWeb:v1.0.0

**Comment by zhihaofans** [comment]
我也是失败了，去jitpack.io看了发现Build失败了 => [build.log](https://jitpack.io/com/github/Victory-Over/SuperWeb/v1.0.0/build.log)

**Comment by Victory-Over** [comment]
已修复，请将版本升级到com.github.Victory-Over:SuperWeb:v1.0.2
