### ISSUE TITLE
可以支持低版本的sdk使用么？

### ISSUE THREAD

**Issue by jiangzehui** [Victory-Over/SuperWeb#6]
在低于sdk 26下无法使用。。。。。

errore resource android: stylerlextAppear ance:Material, widget. Button.Lolored not tound

AGFEI 1 lcind"error, " text""error ta resource andr oid. attr/colorError not found. , " source[f" file "C!N Usersl Admini stratori er adlellcacheslYtr ansforms-1VVfiles-1.1Vappcompat-v7-26 10

. aar8012d81 e698 f09 163872ba9c0cd49fb0resvlus26 values-v26. xml", position" : f"star Line :8, "star tColumn 4, " star tOffset" : 131, " endLine 11, . endC olumn : 12, "endOffset 652111. original"", tool" AAPT"YAGFEI ["kind": érror," texterror.resource andr oid: at tr/ colorError not found. " sources":[f file:"C: Userst ,Admìni str atorAla er adléllcacheslitr ænsforms-1filés-1.1Vappcompat-v7-26.1.0

      ary 8012d81 ë698 Eû9 d63872ba9cÛed49fb0X res, values-v26V values-v26. xml", positionIstar tLine, 12, "star tColumn4, "ster tOffset"657, * endLine15, "endColumn12 endOffset"891H], original"'tool": "AAPT ")

АGРВІ І kіnd""еrrоr, " tехt"," еrrоr: ѕtуlе аttrіbutе Yu027 аndrоіd. аttr/kеуbо аr dЦаvі gаtі оnСluѕtеr Хu0027 nоt fоund. ", " ѕоurсеѕ"[l fіlе"ѕ 'С: UѕеrѕlVАdmіnі ѕtrаtоr и. еr аdlеVсасhеѕVtr аnѕfоrmѕ-1 fіlеѕ-1

      "startE lumn  "startOffset"55. " endLine"5. " endC olumm", 12 erdOffset"2941 H1

**Comment by Victory-Over** [comment]
minSdkVersion 14
targetSdkVersion 26
当然支持26以下版本咯，你这个错误是其他原因导致的，不是SuperWeb 导致的

**Comment by jiangzehui** [comment]
呃。。我意思是 targetSdkVersion 可不可以支持26以下。。
